import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { fetchData } from "../../utils/fetch";
import { url } from "inspector";
import Header from "../../componets/resuse/header";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function ResponsiveRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data:any = await fetchData(`https://strapi-backend-dbhx.onrender.com/api/bgimg`);

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          font-manrope
          min-h-screen 
          w-full
          m-0 
          p-0
        `}
        suppressHydrationWarning={true}
      >
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center bg-white text-6xl text-black">loading ...</div>}>
     <div
          className="fixed top-0 left-0 w-screen h-screen -z-20 bg-cover bg-center md:bg-fixed "
          style={{
            backgroundImage: `url(${data?.imgurl})`,
          }}
        />

     
        <div className="fixed top-0 left-0 w-screen h-screen -z-10 bg-black/50" />

        
          <div className="relative z-10 flex flex-col min-h-screen w-full ">
            <Header />
            
          {children}
        </div>


    </Suspense>
       
        
      
      </body>
    </html>
  );
}
